name: domain
options:
  carthageBuildPath: ../Carthage/Build
targets:
  domain:
    type: framework
    platform: iOS
    deploymentTarget: 9.0
    sources: [Sources]
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: "com.edwin.domain"
        DEVELOPMENT_TEAM: RCM6P6GKXX
        SWIFT_VERSION: 5.0
    dependencies:
      - carthage: RxSwift
        