name: presenter
targets:
  presenter:
    type: framework
    platform: iOS
    deploymentTarget: 9.0
    sources: [Sources]
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: "com.edwin.presenter"
        DEVELOPMENT_TEAM: RCM6P6GKXX
        SWIFT_VERSION: 5.0