name: presenter
options:
  carthageBuildPath: ../Carthage/Build
targets:
  presenter:
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources: [Sources]
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: "com.edwin.presenter"
        DEVELOPMENT_TEAM: RCM6P6GKXX
        SWIFT_VERSION: 5.0
    dependencies:
      - framework: domain.framework
        implicit: true
      - carthage: RxSwift
      - carthage: Cleanse