name: ui
options:
  carthageBuildPath: ../Carthage/Build
targets:
  ui:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources: [Sources,Resources]
    settings:
      base:
        DEVELOPMENT_TEAM: RCM6P6GKXX
        PRODUCT_BUNDLE_IDENTIFIER: "com.edwin.ui"
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
    preBuildScripts:
      - script: "\"$SRCROOT/rswift\" generate \"$SRCROOT/resources/R.generated.swift\""
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/resources/R.generated.swift      
      - script: "if which swiftlint >/dev/null; then swiftlint ; else echo \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\" ; fi"
        name: SwiftLint    
    dependencies:
      - framework: presenter.framework
        implicit: true
      - framework: domain.framework
        implicit: true
      - framework: data.framework
        implicit: true
      - framework: cache.framework
        implicit: true
      - framework: remote.framework
        implicit: true
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Alamofire
      - carthage: RxAlamofire
      - carthage: Cleanse
      - carthage: FLEX
      - carthage: Rswift
      - carthage: Moya
      - carthage: RxMoya
      - carthage: Result
schemes:
  app:
    build:
      targets:
        ui: all
    run:
      config: Debug
      environmentVariables:
        QA: true
    test:
      config: Debug
      environmentVariables:
        - variable: QA
          value: true
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
      revealArchiveInOrganizer: false