name: ui
options:
  carthageBuildPath: ../Carthage/Build
targets:
  ui:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources: [Sources]
    settings:
      base:
        DEVELOPMENT_TEAM: RCM6P6GKXX
        PRODUCT_BUNDLE_IDENTIFIER: "com.edwin.ui"
        SWIFT_VERSION: 5.0
    dependencies:
      - framework: presenter.framework
        implicit: true
      - framework: domain.framework
        implicit: true
      - framework: data.framework
        implicit: true
      - framework: cache.framework
        implicit: true
      - framework: remote.framework
        implicit: true
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Alamofire
      - carthage: RxAlamofire